<?php
session_start();
//require("include/all.php");
require("includes/db_connect.php");
require("includes/functions.php");
require("model/Article.php");
require("model/ArticleRepository.php");
require("pages/ArticleController.php");
require("View/View.php");